FROM alpine:latest

RUN apk add --no-cache bash postgresql-client
RUN apk add --no-cache busybox-suid

# Backup set to run daily at 3am

RUN echo "0 3 * * * /backup.sh >> /var/log/cron.log 2>&1" > /etc/crontabs/root

COPY backup.sh /backup.sh
RUN chmod +x /backup.sh

CMD ["crond", "-f"]
