services:
  postgres:
    build: ./postgres
    container_name: postgres-bot
    restart: unless-stopped
    env_file:
      ../../.env
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  cron-backup:
    build: ./postgres-backup
    container_name: cron-backup-container
    volumes:
      - ${HOST_VOLUME_PATH}:/backups
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      ../../.env

volumes:
  pgdata:
