[[strategies]]
symbol = "ALPH/USDT"
type = "single_edge_liquidity"
identifier = "lab"
taker_exchange = "gate"
maker_exchange = "bitget"
should_match = true
spread = 1.002
min_size_usdt = 10
max_size_usdt = 11

[[exchanges]]
name = "Gate.io"
id = "gate"

[[exchanges]]
name = "Mexc"
id = "mexc"

[[exchanges]]
name = "Bitget"
id = "bitget"
