# Use the official PostgreSQL
FROM postgres:latest

# Set environment variables for the database (optional, customize as needed)
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=arb_bot

# Copy initialization scripts into the container
COPY scripts/*.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432

# Command to run when the container starts
CMD ["postgres"]