from typing import Protocol

class CustomExchange(Protocol):
    name: str
    id: str

    async def create_order(
        self, symbol: str, type: str, side: str, amount: float, price: float, params={}
    ) -> dict: ...
    async def cancel_order(self, id: str, symbol: str) -> dict: ...

    async def fetch_open_orders(
        self,
        symbol: str | None = None,
        since: int | None = None,
        limit: int | None = None,
        params={},
    ) -> list[dict[str, str]]: ...
    async def watch_order_book(self, symbol: str) -> dict: ...

    async def watch_balance(self) -> dict: ...
    async def fetch_balance(self) -> dict: ...
    async def watch_orders(self, symbol: str, since: int) -> list[dict]: ...
    async def close(self): ...
    async def load_markets(self): ...
    
